[project]
name = "sa-submission"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gspread>=6.1.4",
    "pandas>=2.2.3",
    "streamlit>=1.42.2",
]
